optimizer:
  name: adam
  lr: 1.0e-3 # not 1e-3
  weight_decay: 0

train:
  epoch: 1000
  batch_size: 2048
  save_model: false
  loss: pairwise # bpr
  log_loss: false # whether to log loss
  test_step: 3 # evaluate per {test_step} epochs
  patience: 5
  reproducible: true
  seed: 2020
  #pretrain_path: ./checkpoint/xxxx.pth

test:
  metrics: [recall, ndcg] # choose in {ndcg, recall, precision, mrr}
  k: [10, 20, 40] # top-k
  batch_size: 2048 # How many users per batch during validation

data:
  type: general_cf # choose in {general_cf, multi_behavior, sequential, social}
  name: gowalla

model:
  name: lightgcn # case-insensitive
  keep_rate: 0.5
  layer_num: 1
  reg_weight: 1.0e-8
  embedding_size: 64

tune:
  enable: false # Whether to enable grid search to search for optimal hyperparameters
  hyperparameters: [layer_num, reg_weight] # The name of the hyperparameter
  layer_num: [2, 3] # Use a list to store the search range
  reg_weight: [1.0e-6, 1.0e-7, 1.0e-8]
